<?php
namespace Apps\Controllers;

use Cygnite\Common\Input;
use Cygnite\FormBuilder\Form;
use Cygnite\Exception\Handler;
use Cygnite\AssetManager\Asset;
use Cygnite\Validation\Validator;
use Cygnite\Foundation\Application;
use Apps\Models\ShoppingProduct;
use Cygnite\Common\UrlManager\Url;
use Apps\Components\Form\Registration;
use Cygnite\Mvc\Controller\AbstractBaseController;

/**
 * Product Controller - Sample Crud Application
 * This file generated by Cygnite CLI- Crud generator
 */

class ProductsController extends AbstractBaseController
{
    // Plain php layout
    protected $layout = 'layout.base';

    /*
    * Your constructor.
    * @access public
    *
    */
    public function __construct()
    {
        parent::__construct();
    }

    /**
    * Default method for your controller. Render welcome page to user.
    * @access public
    *
    */
    public function indexAction()
    {
        $products = array();
        $products = ShoppingProduct::all(
            array(
                'orderBy' => 'id desc',
                /*'paginate' => array(
                    'limit' => Url::segment(3)
                )*/
            )
        );

        $this->render('index', array(
            'products' => $products,
            'links' => ShoppingProduct::createLinks(),
            'title' => 'Cygnite Framework - Crud Application'
        ));

    }

    /**
     *
     */
    public function typeAction($id = null)
    {
        $input = Input::make();

        $errors =  $validator = null;
        if ($input->hasPost('btnSubmit') == true) {

            $validator = Validator::instance(
                $input,
                function ($validate) {
                        $validate->addRule('product_type', 'required|min:5')
                                        ->addRule('name', 'required|is_string')
                                        ->addRule('price', 'required|is_int');

                    return $validate;
                }
            );

            // Run validation if fail get errors
            if ($validator->run()) {

                if ($id == null || $id == '') {
                    $product = new ShoppingProduct;
                } else {
                    $product = ShoppingProduct::find($id);
                }

                $postArray = $input->except('btnSubmit')->post();

                $product->product_type = $postArray['product_type'];
                $product->name = $postArray['name'];
                $product->price = $postArray['price'];

                if ($product->save()) {
                    $this->setFlash('success', 'Product saved successfully!')
                    ->redirectTo('products/index/'.Url::segment(4));
                } else {
                    $this->setFlash('error', 'Error occured while saving product!')
                            ->redirectTo('products/index/'.Url::segment(4));
                }
            } else {
                //validation error here
                $errors = $validator->getErrors();
            }
        }

        $form = null;

        if (isset($id) && $id !== null) {
            // Update the product
            $product = array();
            $product = ShoppingProduct::find($id);
            $form = new Registration($product, Url::segment(4));
            //$form->errors = $errors;
            $form->validation = $validator;
            $this->edit($id, $form);
        } else {
            //Add a new Product
            $form = new Registration();
           // $form->errors = $errors;
            $form->validation = $validator;// set the validator instance
            $this->add($form);
        }
    }


    /**
     * Add a new Product view page
     * @param type $form
     */
    private function add($form)
    {
        // Since our all all logic is in controller
        // We can also use same view page for create and update
        $this->render('create', array(
            'form' => $form->buildForm()->render(),
            'validation_errors' => $form->errors,
            'title' => 'Add a new Product'
        ));
    }

    /**
     * Call update view page
     * @param type $id
     * @param type $form
     */
    private function edit($id, $form)
    {
        // Since our all all logic is in controller
        // You can also use same view page for create and update
        $this->render('update', array(
            'form' => $form->buildForm()->render(),
            'validation_errors' => $form->errors,
            'title' => 'Update the Product'
        ));
    }

    /**
     *  Display product details
     * @param type $id
     */
    public function showAction($id)
    {
        $product = ShoppingProduct::find($id);

        $this->render('view', array(
            'product' => $product,
            'title' => 'Show the Product'
        ));
    }

    /**
     *  Delete product using id
     *
     * @param type $id
     */
    public function deleteAction($id)
    {
        $product = new ShoppingProduct();

        if ($product->trash($id) == true) {
            $this->setFlash('success', 'Product Deleted Successfully!')->redirectTo('products/');
        } else {
            $this->setFlash('error', 'Error Occured while deleting Product!')->redirectTo('products/');
        }
    }

}//End of your products controller
