<?php 
namespace Apps\Form;

use Cygnite\FormBuilder\Form;
use Cygnite\Foundation\Application;
use Cygnite\Common\UrlManager\Url;

/**
* Sample Form using Cygnite Form Builder
* This file generated by Cygnite CLI Generator.
* You may alter the code to fit your needs
*/

class ProductForm extends Form
{
    //set model object
    private $model;

    public $errors;

    private $segment;

    // We will set action url
    public $action = 'add';
    
    //set validator object
    public $validator;

    public function __construct($object = null, $segment = null)
    {
        // your model object
        $this->model = $object;
        $this->segment = $segment;
    }

    /**
    * Set validator used for displaying validation
    * errors below each form elements
    *
    * @param $validator
    * @return $this
    */
    public function setValidator($validator)
    {
        $this->validator = $validator;

        return $this;
    }

    /**
     *  Build form and return object
     * @return ProductForm
     */
    public function buildForm()
    {
        $id = (isset($this->model->id)) ? $this->model->id : '';

        // Below code is to display validation errors below the input box
        if (is_object($this->validator)) {
            // Set your custom errors
            //$this->validator->setCustomError('column.error', 'Your Custom Error Message');
        }

        $this->open("Product", [
            "method" => "post", "id" => "uniform", "role" => "form",
            "action" => Url::sitePath("product/$this->action/$id/"),
            "style" => "width:500px;margin-top:35px;float:left;"]
        )		->addElement("label", "Product Name", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "product_name", ["value" => (isset($this->model->product_name)) ? $this->model->product_name : "", "class" => "form-control"])
		->addElement("label", "Category", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "category", ["value" => (isset($this->model->category)) ? $this->model->category : "", "class" => "form-control"])
		->addElement("label", "Description", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "description", ["value" => (isset($this->model->description)) ? $this->model->description : "", "class" => "form-control"])
		->addElement("label", "Validity", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "validity", ["value" => (isset($this->model->validity)) ? $this->model->validity : "", "class" => "form-control"])
		->addElement("label", "Price", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "price", ["value" => (isset($this->model->price)) ? $this->model->price : "", "class" => "form-control"])
		->addElement("label", "Created At", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "created_at", ["value" => (isset($this->model->created_at)) ? $this->model->created_at : "", "class" => "form-control"])
		->addElement("label", "Updated At", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "updated_at", ["value" => (isset($this->model->updated_at)) ? $this->model->updated_at : "", "class" => "form-control"])
		->addElement("submit", "btnSubmit", ["value" => "Save", "class" => "btn btn-primary", "style" => "margin-top:15px;" ])
		->close()
		->createForm();



        return $this;
    }

    /**
     * Render form
     * @return type
     */
    public function render()
    {
        return $this->buildForm()->getForm();
    }
}