<?php 
namespace Apps\Form;

use Cygnite\FormBuilder\Form;
use Cygnite\Foundation\Application;
use Cygnite\Common\UrlManager\Url;

/**
* Sample Form using Cygnite Form Builder
* This file generated by Cygnite CLI Generator.
* You may alter the code to fit your needs
*/

class ProductForm extends Form
{
    //set entity object
    protected $entity;

    protected $validator;

    protected $errors = [];

    private $segment;

    // We will set action url
    protected $action = 'add';

    public function __construct($object = null, $segment = null)
    {
        // your model object
        $this->model = $object;
        $this->segment = $segment;
    }


    /**
     * Set form action and request to form builder.
     *
     * @param $action
     * @param $request
     * @return $this
     */
    public function handleRequest($action, $request)
    {
        $this->action = $action;
        $this->setRequest($request);

        return $this;
    }

    /**
     * Set validator used for displaying validation
     * errors below each form elements
     *
     * @param ValidatorInterface $validator
     * @return $this
     */
    public function setValidator(ValidatorInterface $validator)
    {
        $this->validator = $validator;

        return $this;
    }

    /**
     * Get validator instance if set.
     *
     * @return mixed
     */
    public function getValidator()
    {
        return $this->validator;
    }

    /**
     * Set validator object. If object is set you can customize the
     * validator error messages into the form elements.
     *
     * @return void
     */
    public function setValidationErrors($errors)
    {
        $this->errors = $errors;

        return $this;
    }

    /**
     * Get form validation errors.
     *
     * @return mixed
     */
    public function getValidationErrors()
    {
        return ($this->validator instanceof ValidatorInterface && !empty($this->validator->getErrors()))
            ? $this->validator->getErrors()
            : $this->errors;
    }

    /**
     *  Build form and return object
     * @return ProductForm
     */
    public function buildForm()
    {
        $id = (isset($this->model->id)) ? $this->model->id : '';

        // Below code is to display validation errors below the input box
        if (is_object($this->validator) && $this->validator instanceof ValidatorInterface) {
            $this->turnOnErrorElementHighlight(true);
            // Set your custom errors
            //$this->validator->setCustomError('column.error', 'Your Custom Error Message');
        }

        $this->open("Product", [
            "method" => "post", "id" => "uniform", "role" => "form",
            "action" => Url::sitePath("product/$this->action/$id/"),
            "style" => "width:500px;margin-top:35px;float:left;"]
        )		->addElement("label", "Product Name", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "product_name", ["value" => (isset($this->model->product_name)) ? $this->model->product_name : "", "class" => "form-control"])
		->addElement("label", "Category", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "category", ["value" => (isset($this->model->category)) ? $this->model->category : "", "class" => "form-control"])
		->addElement("label", "Description", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "description", ["value" => (isset($this->model->description)) ? $this->model->description : "", "class" => "form-control"])
		->addElement("label", "Validity", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "validity", ["value" => (isset($this->model->validity)) ? $this->model->validity : "", "class" => "form-control"])
		->addElement("label", "Price", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "price", ["value" => (isset($this->model->price)) ? $this->model->price : "", "class" => "form-control"])
		->addElement("label", "Created At", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "created_at", ["value" => (isset($this->model->created_at)) ? $this->model->created_at : "", "class" => "form-control"])
		->addElement("label", "Updated At", ["class" => "col-sm-2 control-label","style" => "width:100%;"])
		->addElement("text", "updated_at", ["value" => (isset($this->model->updated_at)) ? $this->model->updated_at : "", "class" => "form-control"])
		->addElement("submit", "btnSubmit", ["value" => "Save", "class" => "btn btn-primary", "style" => "margin-top:15px;" ])
		->close()
		->createForm();



        return $this;
    }

    /**
     * Render form
     * @return type
     */
    public function render()
    {
        return $this->buildForm()->getForm();
    }
}