<?php 
namespace Apps\Models;

use Cygnite\Database\Schema;
use Cygnite\Common\UrlManager\Url;
use Cygnite\Foundation\Application;
use Cygnite\Database\Cyrus\ActiveRecord;
use Cygnite\Database\Cyrus\ValidationTrait;

/**
* This file is generated by Cygnite CLI Crud generator
*/

class Product extends ActiveRecord
{
    use ValidationTrait;

    //your database connection name
    protected $database = 'cygnite';

    // your table name here
    //protected $tableName = 'product';

    protected $primaryKey = 'id';

    //public $perPage = 5; // used to create pagination links

    /**
    * Set Validation rules for Form
    *
    * @param $input
    * @return mixed
    */
    public $rules = [
		'product_name' => 'required|min:5',
		'category' => 'required|min:5',
		'description' => 'required|min:5',
		'validity' => 'required|min:5',
		'price' => 'required|min:5',
		'created_at' => 'required|min:5',
		'updated_at' => 'required|min:5',
	
    ];

    public function __construct()
    {
        parent::__construct();
    }

    /*
    // Used to set pagination limit
    public function pageLimit()
    {
        return Url::segment(3);
    }
    */
}// End of the Product Model